mysql:
  image: mysql:5.6.23
  environment:
    MYSQL_ROOT_PASSWORD: password
  ports:
    - '3306:3306'
  volumes:
    - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  volumes_from:
    - datastore

redis:
  image: redis:2.8.19
  ports:
    - '6379:6379'
  volumes_from:
    - datastore

memcached:
  image: memcached:1.4.24
  ports:
    - '11211:11211'
  volumes_from:
    - datastore

datastore:
  build: docker/datastore

web:
  build: .
  ports:
    - '3000:3000'
  environment:
    RAILS_ENV: development
    MYSQL_ROOT_PASSWORD: 'password'
    DATABASE_HOST: mysql
    REDIS_HOST: redis
    MEMCACHED_HOST: memcached
  dns:
    - 8.8.8.8
  volumes:
    - ./app:/app
  volumes_from:
    - datastore
  links:
    - mysql
    - redis
    - memcached
